### ISSUE TITLE
A caveat to note

### ISSUE THREAD

**Issue by mungojam** [artyom/cloudfront-autoindex#1]
It turns out that I implemented this at work a few weeks ago, so I was pleased to see somebody else with the same idea.

One minor glitch that we had, and I am assuming you have too is that relative links don't work consistently between somedir/sub and somedir/sub/. In the first case, the current directory is treated as somedir, while in the second case it is treated as somedir/sub, so the same index.html with relative links can't work in both cases.

For us, this isn't a major problem so I probably won't get around to fixing it. The fix would involve adjusting all relative links in one of the two copies of index.html.

Thanks for sharing the cool tool anyway. It popped up on my Google homepage 🙂

**Comment by artyom** [comment]
@mungojam thanks for pointing to this possible issue, I sure ran into this in the past! I'll add a note about this case to the README.

I think that adding a [base html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) to the page can be a workaround for such a scenario.

**Comment by mungojam** [comment]
Thanks 🙂, I didn't know about either of those! I ended up fixing it by generating two different versions of the index.html, but your way sounds much simpler so I may well rewrite it to make it clearer.
